version: '3'
services:
  minio:
    image: quay.io/minio/minio:LATEST
    container_name: zm-minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: testtest
    command: server /data

  createbuckets:
    image: quay.io/minio/mc:LATEST
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio-dev http://minio:9000 test testtest;
      /usr/bin/mc mb minio-dev/test-bucket;
      exit 0;
      "